# yaml-language-server: $schema=https://raw.githubusercontent.com/lalcebo/json-schema/823e19d/serverless/reference.json
service: thatblog
frameworkVersion: '4'

params:
  default:
    ephId: ${env:THATBLOG_EPH_ID, ''}

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  architecture: arm64
  runtime: nodejs24.x
  httpApi:
    name: ${self:service}-${sls:stage}
    payload: '2.0'
    disableDefaultEndpoint: false
  deploymentBucket:
    name: ${self:service}-${sls:stage}-${aws:accountId}-${aws:region}
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: false
    versioning: false
    serverSideEncryption: AES256
  deploymentPrefix: serverless${param:ephId}
  iam:
    role:
      name: ${self:service}-${sls:stage}${param:ephId}-${aws:accountId}-${aws:region}-role
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [DataTable, Arn]
            - Fn::Sub: ['${DataTableArn}/index/*', { DataTableArn: { Fn::GetAtt: [DataTable, Arn] } }]
  environment:
    THATBLOG_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}${param:ephId}
  tags:
    Environment: ${self:provider.stage}
    ProvisionedBy: serverless

functions:
  lambda:
    name: ${self:service}-${sls:stage}${param:ephId}
    handler: lambda.http
    events:
      - httpApi: "*"

build:
  esbuild:
    bundle: true
    buildConcurrency: 1
    minify: false
    sourcemap:
      type: linked
      setNodeOptions: true

plugins:
  - serverless-deployment-bucket
  # - serverless-s3-deploy

custom:
  deploymentBucket:
    versioning: false
    accelerate: false
    blockPublicAccess: false
    policy:
      Version: '2012-10-17'
      Id: MixedAccessBucketPolicy
      Statement:
        - Sid: DenyInsecureTransport
          Effect: Deny
          Principal: '*'
          Action: 's3:*'
          Resource:
            - arn:aws:s3:::${self:provider.deploymentBucket.name}
            - arn:aws:s3:::${self:provider.deploymentBucket.name}/*
          Condition:
            Bool:
              'aws:SecureTransport': 'false'

        - Sid: DenyPublicAccess
          Effect: Deny
          Principal: '*'
          Action: 's3:*'
          Resource:
            - arn:aws:s3:::${self:provider.deploymentBucket.name}
            - arn:aws:s3:::${self:provider.deploymentBucket.name}/${self:provider.deploymentPrefix}/*
          Condition:
            StringNotEqualsIfExists:
              aws:PrincipalAccount: ${aws:accountId}
            Bool:
              aws:PrincipalIsAWSService: 'false'

        - Sid: AllowPublicReadAdminAndThemes
          Effect: Allow
          Principal: '*'
          Action: 's3:GetObject'
          Resource:
            - arn:aws:s3:::${self:provider.deploymentBucket.name}/admin/*
            - arn:aws:s3:::${self:provider.deploymentBucket.name}/themes/*

resources:
  - ${file(./resources.yml)}

    # ServerlessDeploymentBucketPublicAccessBlock:
    #   Type: AWS::S3::BucketPublicAccessBlock
    #   Properties:
    #     Bucket: ${self:provider.deploymentBucket.name}
    #     BlockPublicAcls: false
    #     IgnorePublicAcls: false
    #     BlockPublicPolicy: false
    #     RestrictPublicBuckets: false

    # ServerlessDeploymentBucketPolicy:
    #   Type: AWS::S3::BucketPolicy
    #   # DependsOn: ServerlessDeploymentBucketPublicAccessBlock
    #   Properties:
    #     Bucket: ${self:provider.deploymentBucket.name}
    #     PolicyDocument:
    #       Version: '2012-10-17'
    #       Statement:
    #         - Sid: DenyInsecureTransport
    #           Effect: Deny
    #           Principal: '*'
    #           Action: 's3:*'
    #           Resource:
    #             - arn:aws:s3:::${self:provider.deploymentBucket.name}
    #             - arn:aws:s3:::${self:provider.deploymentBucket.name}/*
    #           Condition:
    #             Bool:
    #               'aws:SecureTransport': 'false'
    #         - Sid: DenyPublicAccessToServerless
    #           Effect: Deny
    #           Principal: '*'
    #           Action: 's3:GetObject'
    #           Resource: arn:aws:s3:::${self:provider.deploymentBucket.name}/serverless/*
    #         - Sid: AllowPublicReadAdminAndThemes
    #           Effect: Allow
    #           Principal: '*'
    #           Action: 's3:GetObject'
    #           Resource:
    #             - arn:aws:s3:::${self:provider.deploymentBucket.name}/admin/*
    #             - arn:aws:s3:::${self:provider.deploymentBucket.name}/themes/*
