name: PR Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: pr-deploy-${{ github.event.number }}

permissions:
  contents: read
  pull-requests: read

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
